export const types = Object.freeze({
    // Sync
    PROFILE_START_FETCHING: 'PROFILE_START_FETCHING',
    PROFILE_STOP_FETCHING: 'PROFILE_STOP_FETCHING',
    PROFILE_FILL: 'PROFILE_FILL',
    PROFILE_SET_FETCHING_ERROR: 'PROFILE_SET_FETCHING_ERROR',

    // Async
    PROFILE_FETCH_BY_USER_ASYNC: 'PROFILE_FETCH_BY_USER_ASYNC',
})
