export const types = Object.freeze({
    // Sync
    HOTELS_START_FETCHING: 'HOTELS_START_FETCHING',
    HOTELS_STOP_FETCHING: 'HOTELS_STOP_FETCHING',
    HOTELS_FILL: 'HOTELS_FILL',
    HOTELS_ADD: 'HOTELS_ADD',
    HOTELS_SET_FETCHING_ERROR: 'HOTELS_SET_FETCHING_ERROR',

    // Async
    HOTELS_FETCH_ASYNC: 'HOTELS_FETCH_ASYNC',
})
