export const types = Object.freeze({
    // Sync
    CITIES_START_FETCHING: 'CITIES_START_FETCHING',
    CITIES_STOP_FETCHING: 'CITIES_STOP_FETCHING',
    CITIES_FILL: 'CITIES_FILL',
    CITIES_SET_FETCHING_ERROR: 'CITIES_SET_FETCHING_ERROR',

    // Async
    CITIES_FETCH_ASYNC: 'CITIES_FETCH_ASYNC',
})
