export const types = Object.freeze({
    // Sync
    TOURS_FILTER_START_FETCHING: 'TOURS_FILTER_START_FETCHING',
    TOURS_FILTER_STOP_FETCHING: 'TOURS_FILTER_STOP_FETCHING',
    TOURS_FILTER_FILL: 'TOURS_FILTER_FILL',
    TOURS_FILTER_SET_FETCHING_ERROR: 'TOURS_FILTER_SET_FETCHING_ERROR',

    // Async
    TOURS_FILTER_FETCH_ASYNC: 'TOURS_FILTER_FETCH_ASYNC',
})
