export const types = Object.freeze({
    // Sync
    TOURS_START_FETCHING: 'TOURS_START_FETCHING',
    TOURS_STOP_FETCHING: 'TOURS_STOP_FETCHING',
    TOURS_FILL: 'TOURS_FILL',
    TOURS_SET_FETCHING_ERROR: 'TOURS_SET_FETCHING_ERROR',

    // Async
    TOURS_FETCH_ASYNC: 'TOURS_FETCH_ASYNC',
})
