export const types = Object.freeze({
    // Sync
    HOTEL_START_FETCHING: 'HOTEL_START_FETCHING',
    HOTEL_STOP_FETCHING: 'HOTEL_STOP_FETCHING',
    HOTEL_FILL: 'HOTEL_FILL',
    HOTEL_ADD: 'HOTEL_ADD',
    HOTEL_SET_FETCHING_ERROR: 'HOTEL_SET_FETCHING_ERROR',

    // Async
    HOTEL_FETCH_ASYNC: 'HOTEL_FETCH_ASYNC',
})
