export const types = Object.freeze({
    // Sync
    AUTH_START_FETCHING: 'AUTH_START_FETCHING',
    AUTH_STOP_FETCHING: 'AUTH_STOP_FETCHING',
    AUTH_FILL: 'AUTH_FILL',
    AUTH_SET_FETCHING_ERROR: 'AUTH_SET_FETCHING_ERROR',
    SET_CREATED_WITH_EMAIL_AND_PASSWORD: 'SET_CREATED_WITH_EMAIL_AND_PASSWORD',
    
    // Async
    AUTH_FETCH_ASYNC: 'AUTH_FETCH_ASYNC',
    AUTH_SIGN_OUT_ASYNC: 'AUTH_SIGN_OUT_ASYNC',
})
