export const types = Object.freeze({
    // Sync
    TOUR_START_FETCHING: 'TOUR_START_FETCHING',
    TOUR_STOP_FETCHING: 'TOUR_STOP_FETCHING',
    TOUR_FILL: 'TOUR_FILL',
    TOUR_SET_FETCHING_ERROR: 'TOUR_SET_FETCHING_ERROR',

    // Async
    TOUR_FETCH_ASYNC: 'TOUR_FETCH_ASYNC',
})
