export const types = Object.freeze({
    // Sync
    ORDERS_START_FETCHING: 'ORDERS_START_FETCHING',
    ORDERS_STOP_FETCHING: 'ORDERS_STOP_FETCHING',
    ORDERS_FILL: 'ORDERS_FILL',
    ORDERS_SET_FETCHING_ERROR: 'ORDERS_SET_FETCHING_ERROR',

    // Async
    ORDERS_FETCH_BY_USER_ASYNC: 'ORDERS_FETCH_BY_USER_ASYNC',
})
